[package]
name = "n64romconvert-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.gtk]
package = "gtk4"
version = "^0.6.6"
features = [
    "v4_8",
    "blueprint",
]